### ISSUE TITLE
Output of running xx_Chamber.m

### ISSUE THREAD

**Issue by zyh929** [AirChem/F0AM#20]
Hello
I have run the MCM_Chamber.m (modified according to ExampleSetup_Chamber.m) for the simulation of atmospheric photochemical reaction process with no constrains. When using different chemical mechanisms, the number of the same species concentration output are different (e.g. when using MCM, S.Conc.HNO3: 241×1 double, when using CB05, S.Conc.HNO3: 194×1 double). I was wondering whether the number of S.Conc.xx can be modified.
In F0AM paper "The Framework for 0-D Atmospheric Modeling (F0AM) v3.1", it says In the second paragraph of part “2 Model description” that “MATLAB is a higher-level language than FORTRAN and can be less computationally efficient; however, it is easier to learn for researchers with little programming experience and is used extensively by the experimental community”. But it took 24 seconds to run a 3-hours simulation by runing MCM_Chamber.m, while it takes 15 hours to run a 3-hours simulation by AtChem(FORTRAN) on HPC. Speed of F0AM is so fast! I was wondering what causes the large difference in simulation speed between F0AM and AtChem.
Thank you very much for your kind consideration. Not sure what I am doing wrong, any assistance would be appreciated, or just fyi.

**Comment by gmwolfe** [comment]
Hello,

Would it be possible for you to post this question on the user forum? I think others would be interested in the answer, and I prefer to keep model communications in a public area.

https://groups.google.com/g/f0amusers

The short answer to your first question is that the number of outputs with ModelOptions.EndPointsOnly = 0 will vary because the ode15s solver adjusts its internal timestep based on the stiffness of the differential equations. MCM has more reactions and includes a lot of very fast reactions, whereas CB05 is condensed. So, MCM is a stiffer set of equations (larger range in reaction rates).

I haven't used AtChem, but I can tell you that it is possible to make F0AM run very slow with the introduction of a typo. Order-of-magnitude errors in rate coefficients or initial conditions are the usual culprit.

Thank you,

Glenn M. Wolfe
NASA Goddard Space Flight Center
Atmospheric Chemistry and Dynamics Laboratory
Office: 301.614.6008<tel:301.614.6008>
Lab:     301.614.6925<tel:301.614.6925>
***@***.******@***.***> | https://sites.google.com/site/wolfegm/



From: zyh929 ***@***.***>
Sent: Sunday, September 25, 2022 12:47 AM
To: AirChem/F0AM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [AirChem/F0AM] Output of running xx_Chamber.m (Issue #20)


Hello
I have run the MCM_Chamber.m (modified according to ExampleSetup_Chamber.m) for the simulation of atmospheric photochemical reaction process with no constrains. When using different chemical mechanisms, the number of the same species concentration output are different (e.g. when using MCM, S.Conc.HNO3: 241×1 double, when using CB05, S.Conc.HNO3: 194×1 double). I was wondering whether the number of S.Conc.xx can be modified.
In F0AM paper "The Framework for 0-D Atmospheric Modeling (F0AM) v3.1", it says In the second paragraph of part "2 Model description" that "MATLAB is a higher-level language than FORTRAN and can be less computationally efficient; however, it is easier to learn for researchers with little programming experience and is used extensively by the experimental community". But it took 24 seconds to run a 3-hours simulation by runing MCM_Chamber.m, while it takes 15 hours to run a 3-hours simulation by AtChem(FORTRAN) on HPC. Speed of F0AM is so fast! I was wondering what causes the large difference in simulation speed between F0AM and AtChem.
Thank you very much for your kind consideration. Not sure what I am doing wrong, any assistance would be appreciated, or just fyi.

-
